#!/bin/bash
export SAVEPATH=$PATH
. /etc/environment
export PATH=$PATH:$SAVEPATH
export JAVA_HOME

current_hadoop_ver=`/usr/lib/hadoop/bin/hadoop version|head -n1|awk '{print $2}'`
new_hadoop_ver=`action-get version`
cpu_arch=`lscpu|grep -i arch|awk '{print $2}'`
rollback=`action-get rollback`


if pgrep -f Dproc_resourcemanager ; then 
        action-set result="resourcemanager process detected, upgrade aborted"
        status-set active "resourcemanager process detected, upgrade aborted" 
        exit 1
fi

if [ "$new_hadoop_ver" == "$current_hadoop_ver" ] ; then 
        action-set result="Same version already installed, aborting"
        action-fail "Same version already installed"
        exit 1
fi

if [ "${rollback}" == "True" ] ; then
        if [ -d /usr/lib/hadoop-${new_hadoop_ver} ] ; then
                rm /usr/lib/hadoop
                ln -s /usr/lib/hadoop-${new_hadoop_ver} /usr/lib/hadoop
                if [ -d /usr/lib/hadoop-${current_hadoop_ver}/logs ] ; then
                        mv /usr/lib/hadoop-${current_hadoop_ver}/logs /usr/lib/hadoop/
                fi
        fi
                action-set newhadoop.rollback="successfully rolled back"
                status-set active "Ready - rollback to ${new_hadoop_ver} complete"
                exit 0
fi
                
status-set maintenance "Fetching hadoop-${new_hadoop_ver}-${cpu_arch}"
juju-resources fetch hadoop-${new_hadoop_ver}-${cpu_arch}
if [ ! $? -eq 0 ] ; then
        action-set newhadoop.fetch="fail"
        exit 1
fi
action-set newhadoop.fetch="success"

status-set maintenance "Verifying hadoop-${new_hadoop_ver}-${cpu_arch}"
juju-resources verify hadoop-${new_hadoop_ver}-${cpu_arch}
if [ ! $? -eq 0 ] ; then
        action-set newhadoop.verify="fail"
        exit 1
fi
action-set newhadoop.verify="success"

new_hadoop_path=`juju-resources resource_path hadoop-${new_hadoop_ver}-${cpu_arch}`
if [ -h /usr/lib/hadoop ] ; then
       rm /usr/lib/hadoop
fi

mv /usr/lib/hadoop/ /usr/lib/hadoop-${current_hadoop_ver}
ln -s /usr/lib/hadoop-${current_hadoop_ver}/ /usr/lib/hadoop
current_hadoop_path=hadoop-${current_hadoop_ver}

status-set maintenance "Extracting hadoop-${new_hadoop_ver}-${cpu_arch}"
tar -zxvf ${new_hadoop_path} -C /usr/lib/
if [ $? -eq 0 ] ; then
        if [ -h /usr/lib/hadoop ] ; then
                rm /usr/lib/hadoop
        fi
        ln -s /usr/lib/hadoop-${new_hadoop_ver} /usr/lib/hadoop
fi
if [ -d ${current_hadoop_path}/logs ] ; then
        mv ${current_hadoop_path}/logs ${new_hadoop_path}/
fi

# set hadoop.version in unitdata
chlp unitdata set hadoop.version ${new_hadoop_ver}

hooks/config-changed

action-set result="complete"
status-set active "Ready - hadoop version ${new_hadoop_ver} installed"
