#!/bin/bash

if ! charms.reactive is_state 'resourcemanager.ready'; then
    action-fail 'ResourceManager not yet ready'
    exit
fi

if command -v systemctl >/dev/null; then
  # assume systemd
  systemctl restart resourcemanager
  systemctl restart historyserver
elif command -v service >/dev/null; then
  # assume upstart
  service resourcemanager restart
  service historyserver restart
fi
