#!/bin/bash
set -ex

if ! charms.reactive is_state 'resourcemanager.ready'; then
    action-fail 'ResourceManager not yet ready'
    exit
fi

IN_DIR='smoke_test_in'
OUT_DIR='smoke_test_out'
SIZE=10000
OPTIONS=''

MAPS=1
REDUCES=1
NUMTASKS=1
COMPRESSION='LocalDefault'

OPTIONS="${OPTIONS} -D mapreduce.job.maps=${MAPS}"
OPTIONS="${OPTIONS} -D mapreduce.job.reduces=${REDUCES}"
OPTIONS="${OPTIONS} -D mapreduce.job.jvm.numtasks=${NUMTASKS}"
if [ $COMPRESSION == 'Disable' ] ; then
        OPTIONS="${OPTIONS} -D mapreduce.map.output.compress=false"
elif [ $COMPRESSION == 'LocalDefault' ] ; then
        OPTIONS="${OPTIONS}"
else
        OPTIONS="${OPTIONS} -D mapreduce.map.output.compress=true -D mapred.map.output.compress.codec=org.apache.hadoop.io.compress.${COMPRESSION}Codec"
fi

# create dir to store results
RUN=`date +%s`
RESULT_DIR=/opt/terasort-results
RESULT_LOG=${RESULT_DIR}/${RUN}.$$.log
mkdir -p ${RESULT_DIR}
chown -R ubuntu:ubuntu ${RESULT_DIR}

# clean out any previous data (must be run as ubuntu)
su ubuntu << EOF
if hadoop fs -stat ${IN_DIR} &> /dev/null; then
    hadoop fs -rm -r -skipTrash ${IN_DIR} || true
fi
if hadoop fs -stat ${OUT_DIR} &> /dev/null; then
    hadoop fs -rm -r -skipTrash ${OUT_DIR} || true
fi
EOF

START=`date +%s`
# NB: Escaped vars in the block below (e.g., \${HADOOP_HOME}) come from
# /etc/environment while non-escaped vars (e.g., ${IN_DIR}) are parameterized
# from this outer scope
su ubuntu << EOF
. /etc/environment
echo 'generating data'
hadoop jar \${HADOOP_HOME}/share/hadoop/mapreduce/hadoop-mapreduce-examples*.jar teragen ${SIZE} ${IN_DIR} &>/dev/null
echo 'sorting data'
hadoop jar \${HADOOP_HOME}/share/hadoop/mapreduce/hadoop-mapreduce-examples*.jar terasort ${OPTIONS} ${IN_DIR} ${OUT_DIR} &> ${RESULT_LOG}
EOF
STOP=`date +%s`

if ! grep -q 'Bytes Written=1000000' ${RESULT_LOG}; then
    action-fail 'smoke-test failed'
    action-set log="$(cat ${RESULT_LOG})"
fi
DURATION=`expr $STOP - $START`
