#!/bin/bash

if ! charms.reactive is_state 'resourcemanager.ready'; then
    action-fail 'ResourceManager not yet ready'
    exit
fi

if command -v systemctl >/dev/null; then
  # assume systemd
  systemctl start resourcemanager
  systemctl start historyserver
elif command -v service >/dev/null; then
  # assume upstart
  service resourcemanager start
  service historyserver start
fi
