#!/bin/bash

if ! charms.reactive is_state 'resourcemanager.ready'; then
    action-fail 'ResourceManager not yet ready'
    exit
fi

if command -v systemctl >/dev/null; then
  # assume systemd
  systemctl stop resourcemanager
  systemctl stop historyserver
elif command -v service >/dev/null; then
  # assume upstart
  service resourcemanager stop
  service historyserver stop
fi
